/** @type {import('tailwindcss').Config} */
module.exports = {
	content: ['./src/**/*.{html,js,jsx}'],
	theme: {
		extend: {},
		colors: {
			black: '#000',
			'error-dark': '#721c24',
			'error-light': '#f5c6cb',
			'link-blue': '#00d',
			'rail-black': '#222',
			'rail-darkblue': '#2b2d42',
			'rail-darkblue-dark': '#1c1d2a',
			'rail-darkblue-light': '#3a3d5a',
			'rail-gray': '#8d99ae',
			'rail-gray-dark': '#76849e',
			'rail-gray-light': '#a4aebe',
			'rail-pink': '#ef233c',
			'rail-pink-dark': '#db1029',
			'rail-pink-light': '#f2485c',
			'rail-red': '#d90429',
			'rail-red-dark': '#b20322',
			'rail-red-light': '#fa0a34',
			'rail-white': '#edf2f4',
			'rail-white-dark': '#e1e9ed',
			'rail-white-light': '#f9fbfb',
			'success-dark': '#165824',
			'success-light': '#d4eddd',
			'warning-dark': '#960',
			'warning-light': '#ffeeba',
			white: '#fff',
		},
	},
	plugins: [],
};
